version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=battlesnake
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=battlesnake
      - MYSQL_USER=battlesnake
      - MYSQL_PASSWORD=battlesnake
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - battlesnake-network
    depends_on:
      - mysql

  caddy:
    image: caddy:2
    ports:
      - "8088:80"
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - .:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - battlesnake-network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=battlesnake
      - MYSQL_USER=battlesnake
      - MYSQL_PASSWORD=battlesnake
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/seed/:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql
    networks:
      - battlesnake-network

networks:
  battlesnake-network:
    driver: bridge

volumes:
  mysql-data:
  caddy_data:
  caddy_config:
